### ISSUE TITLE
Preserving data?

### ISSUE THREAD

**Issue by tmcw** [mbostock/us-atlas#14]
In each step of this Makefile, the data from the original shapefiles is thrown away by not specifying `-p`. Is the expectation that it would be joined back in with another tool?

I'm tinkering with a version of this 'for dummies' that would have pre-built data, preserve a minimum of properties, and aim for that <1MB threshold that's web-map-friendly. Thoughts?

**Comment by tmcw** [comment]
Okay, cool - the default in this project makes a lot of sense for semi-pro or pro users.

**Comment by mbostock** [comment]
Related: I would eventually like to extract the property-modifying features out of the topojson command-line tool and put them into a separate tool. This probably means removing the --id-property, --properties, and --external-properties arguments and just having the topojson command always pass-through input properties. Then there would be a separate tool (or tools!) for filtering, transforming and joining properties. A tool that could presumably work with either TopoJSON or GeoJSON.

**Comment by mbostock** [comment]
Related mbostock/topojson#271.
