### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by jonataswalker** [mbostock/us-atlas#17]
Hi there!

To make the git clone work I made some adjustments as it follows:
1) download v0.0.4 tar.gz released
2) git clone repo(obvious)
3) replace cloned Makefile content with tar gzipped version
4) change the path of binary topojson - line 4
5) replace cloned geomerge content with topomerge tar gzipped version (both bin dir)
6) replace cloned geouniq content with topouniq tar gzipped version (both bin dir)

Now I can run make all, make topo/us-10m.json and so on.
Many thanks for your software.

**Comment by mbostock** [comment]
Closing old issues. Sorry I never replied.
