### ISSUE TITLE
make streamflow data

### ISSUE THREAD

**Issue by bjvogt** [mbostock/us-atlas#19]
I probably ought not be getting my feet wet with D3 via custom topojson, but here I am.  

I've got things installed so that I can make us/us-10m.json but make all does not work.  

I'd most particularly like to work with the watershed boundary data.  

How do I roll my own make requests against the strream data?  Only example I can find is the png in the samples of this us-atlas repo.  

thanks!

**Comment by mbostock** [comment]
Closing old issues. Sorry I never replied.
