### ISSUE TITLE
Support for city/town

### ISSUE THREAD

**Issue by micheleorsi** [mbostock/us-atlas#20]
I am trying to perform a data visualization with information about cities/towns, but I don't find any way how to extract such borders.
Are these information available in the original shapefile? Is it possible to extract in some ways these information?

**Comment by jbielick** [comment]
@micheleorsi, for the US, you can find citiy shapefiles here: ftp://ftp2.census.gov/geo/tiger/TIGER2014/PLACE/

**Comment by micheleorsi** [comment]
Thanks so much @jbielick! I will try in the next days!

**Comment by mbostock** [comment]
Closing old issues. Sorry I never replied.
