### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by factormystic** [mbostock/us-atlas#3]
Cloned the repo, ran `npm install`, then `make`, and got this error:

    Makefile:249: *** mixed implicit and normal rules.  Stop.

I inspected the makefile and see that the offending block appears to be

    shp/us/zipcodes.shp shp/%/tracts.shp shp/%/blockgroups.shp shp/%/blocks.shp:
    	rm -rf $(basename $@) && mkdir -p $(basename $@) && unzip -d $(basename $@) $<
    	for file in $(basename $@)/*; do chmod 644 $$file; mv $$file $(basename $@).$${file##*.}; done
    	rmdir $(basename $@)
    	touch $@

A quick googling shows some discussions about the mixing of paths with and without the `%` character, so perhaps that's the cause? I'm afraid I don't know enough about makefiles to offer a solution.

**Comment by mbostock** [comment]
Sorry I never replied. I’m closing old issues as I am going to do some redesigns here. If it helps, a fix was proposed in #9.
